### ISSUE TITLE
Getting "Status: Error Fetching Data" when trying to connect to my EP lite.

### ISSUE THREAD

**Issue by tommydadog** [EverythingSmartHome/everything-presence-addons#29]
Hi, I am getting this error when trying to connect to my EP lite "Status: Error Fetching Data" next to the "Stop Refresh" button.

It will not fetch sensor data from the EP lite but I can draw zones randomly in the configurator and it will update the zones in HA. I also can't find anything in the log files on what is causing it.

I have tried to reflash it from the web flashing tool, changed USB power supply, connecting to same WiFi/vlan as HA server and the problem still there.

Any help would be appreciated.

**Comment by EverythingSmartHome** [comment]
Hello,

Make sure to enable all zones in Home Assistant. Zone 1 is enabled by default but zone 2-4 are hidden (so as not to overwhelm new users). You would need to just unhide these entities in HA which should resolve the issue

**Comment by tommydadog** [comment]
Hi Lewis, that has fixed it! 

Thank you.

**Comment by grigi** [comment]
Hi Lewis, could you please consider adding a tooltip or link in the app to a wiki hosted here with some standard Q&A like this?

**Comment by gabors11** [comment]
Hey, I have enabled all controls in Home Assistant but still getting this error. I have also installed the latest firmware version (1.2.2) and restarted everything several times. Is there any other possible know cause?
